create table var (
    id INTEGER not null primary key autoincrement,
    name TEXT not null default ""
);
create table value (
    id INTEGER not null primary key autoincrement,
    var_id INTEGER not null,
    value TEXT not null default "",
    foreign key(var_id) references var(id)
);
create table regex (
    id INTEGER not null primary key autoincrement,
    expression TEXT not null default "",
    "action" text not null default "",
    sub TEXT not null default "",
    mention BOOLEAN default false
);
create table fact (
    id INTEGER not null primary key autoincrement,
    fact TEXT not null,
    tidbit TEXT not null,
    verb TEXT not null
);
insert into regex (expression, action, mention)
values ('(.*?)(<reply>)(.*)', 'add', true),
    ('(.*?)(<action>)(.*)', 'add', true),
    ('^forget that$', 'forget', true),
    ('^what was that\??$', 'inquiry', true),
    ('^add \$(\w+) (\w+)', 'add_var', true),
    ('^remove \$(\w+) (\w+)', 'remove_var', true);
insert into var (name)
values ('noun'),
    ('verb'),
    ('adjective');
insert into value (var_id, value)
values (1, 'acid'),
    (1, 'acorn'),
    (1, 'bacon'),
    (1, 'battery'),
    (1, 'beef'),
    (1, 'cake'),
    (1, 'comic'),
    (1, 'device'),
    (1, 'factoid'),
    (1, 'galaxy'),
    (1, 'idea'),
    (1, 'magic'),
    (1, 'mindjail'),
    (1, 'phone'),
    (1, 'potato'),
    (1, 'salami'),
    (1, 'shirt'),
    (1, 'sword'),
    (1, 'tooth'),
    (1, 'wrench'),
    (1, 'cheese'),
    (1, 'China'),
    (1, 'computer'),
    (1, 'cereal'),
    (1, 'soda'),
    (1, 'ham'),
    (1, 'tea'),
    (1, 'keyboard'),
    (1, 'door'),
    (1, 'floor'),
    (1, 'straw'),
    (1, 'cup'),
    (1, 'hat'),
    (1, 'electrode'),
    (1, 'cloth'),
    (1, 'vagina'),
    (1, 'teeth'),
    (1, 'key'),
    (1, 'lock'),
    (1, 'bag'),
    (1, 'laptop'),
    (1, 'dog'),
    (1, 'cat'),
    (1, 'touchscreen'),
    (1, 'bunny'),
    (1, 'powersupply'),
    (1, 'DeLorean'),
    (1, 'pinball'),
    (1, 'screw'),
    (1, 'code'),
    (1, 'dong'),
    (2, 'hug'),
    (2, 'kiss'),
    (2, 'listen'),
    (2, 'run'),
    (2, 'shriek'),
    (2, 'sleep'),
    (2, 'smash'),
    (2, 'talk'),
    (2, 'walk'),
    (2, 'screw'),
    (2, 'write'),
    (2, 'code'),
    (2, 'drink'),
    (2, 'eat'),
    (2, 'nom'),
    (2, 'kill'),
    (2, 'grope'),
    (2, 'ram'),
    (2, 'learn'),
    (2, 'spam'),
    (2, 'fuck'),
    (4, 'adorable'),
    (4, 'cold'),
    (4, 'fast'),
    (4, 'fuzzy'),
    (4, 'gigantic'),
    (4, 'hairless'),
    (4, 'hairy'),
    (4, 'hot'),
    (4, 'huge'),
    (4, 'iridescent'),
    (4, 'lukewarm'),
    (4, 'moldy'),
    (4, 'repulsive'),
    (4, 'rough'),
    (4, 'royal'),
    (4, 'sharp'),
    (4, 'shiny'),
    (4, 'slow'),
    (4, 'smelly'),
    (4, 'smooth'),
    (4, 'sparkly'),
    (4, 'spicy'),
    (4, 'spikey'),
    (4, 'spooky'),
    (4, 'squishy'),
    (4, 'sticky'),
    (4, 'tangy'),
    (4, 'tiny'),
    (4, 'warm'),
    (4, 'windy'),
    (4, 'wonky');
insert into fact (fact, tidbit, verb)
values (
        'how',
        'How much $noun could a $noun $verb, if a $noun could $verb $nouns?',
        '<reply>'
    ),
    ('yay', 'boogies!', '<action>');
